"""initial tables

Revision ID: e70f8b644be7
Revises: 
Create Date: 2026-08-12 13:32:19.655909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e70f8b644be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('arcade_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_arcade_user_id', 'users', ['arcade_user_id'], unique=False)
    op.create_index('ix_users_external_user_id', 'users', ['external_user_id'], unique=False)
    op.create_table('threads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_status', 'threads', ['status'], unique=False)
    op.create_index('ix_threads_user_id', 'threads', ['user_id'], unique=False)
    op.create_table('interrupts',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interrupts_status', 'interrupts', ['status'], unique=False)
    op.create_index('ix_interrupts_thread_id', 'interrupts', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interrupts_thread_id', table_name='interrupts')
    op.drop_index('ix_interrupts_status', table_name='interrupts')
    op.drop_table('interrupts')
    op.drop_index('ix_threads_user_id', table_name='threads')
    op.drop_index('ix_threads_status', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_users_external_user_id', table_name='users')
    op.drop_index('ix_users_arcade_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
